### ISSUE TITLE
conf 更新问题

### ISSUE THREAD

**Issue by wao1201** [lizhaode/SpechtLiteConf#1]
首先感谢您的分享，已经顺利跑起来了，现有个小问题：

请问这个以后要更新规则的话，就 clone 了然后 pull 一下就好了吗？我尝试运行了 newRules.py，终端提示 syntax error

谢谢

**Comment by wao1201** [comment]
在 Mac 和 Ubuntu 上都试了，同样的错误：

  File "/Users/  /Documents/Dev/SpechtLiteConf/newRules.py", line 7
SyntaxError: Non-ASCII character '\xe8' in file /Users/  /Documents/Dev/SpechtLiteConf/newRules.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by lizhaode** [comment]
@wao1201 你是用Python2运行的吧。第7行是中文注释中，在Python3上不需要特殊的配置，但是Python2中需要在py文件中注明UTF-8编码格式

另外，我在README中写到了，这个已经改成用一个shadowrocket配置来转成SpechtLite的配置，但是shadowrocket那个项目维护的内容变了，我还没有更新，而且目前其实除了广告屏蔽的配置，其他的并不需要太大的更新，如果有单独需要更新的，我会手动更新conf文件夹中的配置文件

所以，理论上，直接git pull，然后直接取出来conf文件夹中更新的文件到自己的配置文件中即可

**Comment by wao1201** [comment]
@lizhaode 好的，明白了

另分享下自己用的两个规则源：
手机上用的（小火箭） https://github.com/lhie1/Surge
台式机以前用的（NG） https://github.com/ACL4SSR/ACL4SSR

希望可以帮助到您

再次感谢作者您

**Comment by lizhaode** [comment]
@wao1201 
多谢，我用你发的ACL那个项目中的广告更新了一把
